### PR TITLE
Adding French Translation to notifications

### PR DESCRIPTION
**Pull request by HoM3r17**
Everything is in the title :)

### CODE REVIEW

**Comment by mundschenk-at** [comment]
Hi, why did you close the PR?

**Comment by HoM3r17** [comment]
Sorry, my mistake, first PR and wanted to update the readme file as well.

**Comment by mundschenk-at** [comment]
For the future, you can use `git rebase -i` to interactively clean up your commit history and then do a forced push (`git push -f`) to your branch.

**Comment by mundschenk-at** [comment]
Also if it's the same branch, you can just edit the PR description/title.

**Comment by HoM3r17** [comment]
Thanks for the tips ;)

**Pull request closed without merging**
